"""empty message

Revision ID: 347523dff2b0
Revises: b39423f534c5
Create Date: 2022-10-09 23:27:05.920385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '347523dff2b0'
down_revision = 'b39423f534c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slug', sa.String(length=20), nullable=True))
    op.drop_column('users', 'slug_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slug_id', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('users', 'slug')
    # ### end Alembic commands ###
