"""added hand in date for the task

Revision ID: 6e4ac9e3bb44
Revises: 48fb5f91142f
Create Date: 2022-10-27 14:32:38.987865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4ac9e3bb44'
down_revision = '48fb5f91142f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('hand_in_by', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'hand_in_by')
    # ### end Alembic commands ###
